version: 0.0

os: ubuntu

files:
  - source: /
    destination: /root/ncp-user/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60