spring:
  profiles:
    include: database, log
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true