name: CI with Gradle

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'master'
      - 'feature/*'

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: make application-database.properties
        run: |
          cd ./src/main/resources
          touch ./application-database.properties
          echo "${{ secrets.DATABASE }}" >> ./application-database.properties
        shell: bash

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Publish Unit Test Result
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/one-delivery-web .
          docker push ${{ secrets.DOCKER_REPO }}/one-delivery-web

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/one-delivery-web
            sudo docker pull ${{ secrets.DOCKER_REPO }}/one-delivery-nginx
            docker-compose up -d
            docker image prune -f
  
